name: Build & Test (macos & linux)

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build+Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
