name: Build & Test (macos & linux)

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build+Test
    uses: swift-libp2p/github-workflows/.github/workflows/build+test.yml@main
